# docker/Dockerfile.streamlit
FROM python:3.11-slim

# --------------------------------------------------
# Variables d'environnement
# --------------------------------------------------
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# --------------------------------------------------
# Répertoire de travail
# --------------------------------------------------
WORKDIR /app

# --------------------------------------------------
# Upgrade pip
# --------------------------------------------------
RUN pip install --upgrade pip setuptools wheel

# --------------------------------------------------
# Installer les dépendances Streamlit
# --------------------------------------------------
COPY requirements_streamlit.txt .
RUN pip install --no-cache-dir -r requirements_streamlit.txt

# --------------------------------------------------
# Copier l’interface Streamlit
# --------------------------------------------------
COPY interface ./interface

# --------------------------------------------------
# Exposer le port
# --------------------------------------------------
EXPOSE 8501

# --------------------------------------------------
# Lancer Streamlit
# --------------------------------------------------
CMD ["streamlit", "run", "interface/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
